class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror'
        self.UnzipMirrorCommand = 'unzipmirror'
        self.TarMirrorCommand = 'tarmirror'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'look'
        self.StatusCommand = 'status'
        self.AuthorizeCommand = 'auth'
        self.UnAuthorizeCommand = 'unauth'
        self.AuthListCommand = 'users'
        self.PingCommand = 'ping'
        self.RestartCommand = 'reboot'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone'
        self.WatchCommand = 'watch'
        self.TarWatchCommand = 'tarwatch'
        self.DeleteCommand = 'dx'
        self.UsageCommand = 'usage'
        self.RepoCommand = 'repo'

BotCommands = _BotCommands()
